version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: bro-mine-server
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
      - ./plugins:/data/plugins
      - ./world:/data/world
      - ./world_nether:/data/world_nether
      - ./world_the_end:/data/world_the_end
      - ./config:/data/config
    environment:
      MOTD: "§k§l§c>>>§r§l§e⚡§bBro§dMine§6Server§e⚡§c<<< §r§n§5Aniversário §6Arthur §aEdition §4Seus §9Viadim §k§l!!!"
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.7"
      MEMORY: "4G"
      ONLINE_MODE: "false"
      MAX_PLAYERS: "10"
    restart: unless-stopped
